'use client'

import { Kreon, Poppins } from 'next/font/google'
import Container from '@mui/material/Container';
import { CssBaseline } from '@mui/material';

const kreon = Kreon({ subsets: ['latin'] })
const poppins = Poppins({ weight: '300', subsets: ['latin'] })


import { createTheme, ThemeProvider } from '@mui/material/styles';
// Define tu paleta de colores personalizada
const theme = createTheme({
  palette: {
    primary: {
      main: '#FF944D', // Cambia el color principal
    },
    secondary: {
      main: '#4B83FC', // Cambia el color secundario
    },
    // Otros colores personalizados
  },
  typography: {
    fontFamily: {kreon}, // Fuente principal
    body1: {
      fontFamily: { poppins }, // Fuente secundaria para párrafos
    },
  }
});

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({ children }) {
  return (
    <ThemeProvider theme={theme}>
      <html lang="es">
        <body className={`${kreon.className} ${poppins.className}`}>
          <CssBaseline />
          <Container maxWidth="sm">
          </Container>
          {children}
        </body>
      </html>
    </ThemeProvider>
  )
}
